
// Objective-C API for talking to the following Go packages
//
//	github.com/coredns/coredns/coremain
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Coremain_FRAMEWORK_H__
#define __Coremain_FRAMEWORK_H__

#include "Coremain.objc.h"
#include "Universe.objc.h"

#endif
