
// Objective-C API for talking to the following Go packages
//
//	github.com/coredns/coredns/core/dnsserver
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Dnsserver_FRAMEWORK_H__
#define __Dnsserver_FRAMEWORK_H__

#include "Dnsserver.objc.h"
#include "Universe.objc.h"

#endif
